server:
  port: 3000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/activosf
    username: activosf
    password: qazwsx

  jpa:
    #show-sql: true  
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: none
        
    properties:
      hibernate:
        default_batch_fetch_size: 500
        #format_sql: true
        #use_sql_comments: true

security:
  key:
    private: classpath:app.key
    public: classpath:app.pub

decorator:
  datasource:
    p6spy:
      enable-logging: true

# swagger

springdoc:
  swagger-ui:
    path: /activosf-documentation
    tryItOutEnabled: true
    ui.filter: true
  api-docs:
    path: /activosf-api-docs

activosf:
  openapi:
    dev-url: http://localhost:3000
    prod-url: https://gob.gamo.org