package gob.gamo.activosf.app.dto;

public enum CriteriosBusquedaEnum {
    CODIGO_ACTIVO,
    PARTIDAS_PRESUPUESTARIAS,
    CODIGOS_CONTABLES,
    FAMILIAS,
    SUB_FAMILIAS,
    CENTRO_COSTO,
    FUENTE_FINANCIAMIENTO,
    ORGANISMO_FINANCIADOR,
    AMBIENTES,
    AREAS,
    TIPO_ASIGNACION,
    ESTADO,
    COSTO,
    FECHA_HISTORICA,
    ESTADO_USO_ACTIVO,
    TIPO_ACTUALIZACION,
    GESTION,
    PROVEEDOR,
    USUARIO_ASIGNADO,
    SOLO_REVALUADOS;
}
