-- roles
insert into sec_roles (rol_id, rol_codrol, rol_descrip) values (1, 'USUARIO AAFF Y ALMACENES', 'USUARIO AAFF Y ALMACENES');
insert into sec_roles (rol_id, rol_codrol, rol_descrip) values (2, 'RESPONSABLE AAFF', 'RESPONSABLE AAFF        ');
insert into sec_roles (rol_id, rol_codrol, rol_descrip) values (3, 'CONTRATACIONES', 'CONTRATACIONES          ');
insert into sec_roles (rol_id, rol_codrol, rol_descrip) values (5, 'ADMINISTRADOR SISTEMAS', 'ADMINISTRADOR SISTEMAS  ');
insert into sec_roles (rol_id, rol_codrol, rol_descrip) values (6, 'RESPONSABLE ALMACENES', 'RESPONSABLE ALMACENES   ');
insert into sec_roles (rol_id, rol_codrol, rol_descrip) values (7, 'CONTABILIDAD', 'CONTABILIDAD            ');


-- recursos

INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (1 , 'ASIGNACIONES','MIS ASIGNACIONES' ,'/ACTIVOFIJOASIGNADO/LISTAFACTIVOFIJO.XHTML');       
INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (2 , 'RECEPCION' ,'RECEPCIÓN' ,'/AFNOTARECEPCION/MANAGENOTARECEPCION.XHTML');
INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (3 , 'GESTION AF' ,'GESTION DE ACTIVOS FIJOS' ,'/AFACTIVOFIJO/LISTAFACTIVOFIJO.XHTML');

INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (25 , 'INGRESO DE MATERIALES','INGRESO DE MATERIALES','/AFALTAMATERIAL/LISTAFALTAMATERIAL.XHTML');
INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (5 , 'BAJA DE MATERIALES','BAJA DE MATERIALES','/AFBAJAMATERIAL/LISTAFBAJAMATERIAL.XHTML');
INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (6 , 'SOLICITUD DE MATERIALES' ,'SOLICITUD DE MATERIALES' ,'/AFSOLICITUDDEMATERIAL/MANAGEAFSOLICITUDDEMATERIAL.XHTML');
INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (7 , 'KARDEX DE MATERIALES','KARDEX DE MATERIALES','/REPORTESALMACENES/KARDEXMATERIALALMACEN.XHTML');
INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (8 , 'REPORTE EXISTENCIA MATER','REPORTE DE EXISTENCIA DE MATERIALES','/REPORTESALMACENES/REPORTEEXISTENCIAS.XHTML');
INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (9 , 'REPORTE MOVIMIENTOS POR ALM','REPORTE DE MOVIMIENTOS POR ALMACEN Y MATERIAL','/REPORTESALMACENES/LISTREGISTROKARDEXMATERIALALMACEN.XHTML');

INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (10,  'BUSCADOR','BUSCADOR AVANZADO DE ACTIVOS FIJOS' ,'/REPORTES/BUSCADORAVANZADO.XHTML');
INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (11,  'ASIGNACION AF' ,'ASIGNACIÓN DE ACTIVOS FIJOS' ,'/REPORTES/ASIGNACIONUSUARIO.XHTML');
INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (12,  'REPORTE UFV','REPORTE DE UNIDAD DE FOMENTO A LA VIVIENDA' ,'/AFTIPOCAMBIO/LISTAFTIPOCAMBIO.XHTML');
INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (13,  'INVENTARIO TOTAL AF CIERRE','INVENTARIO TOTAL DE ACTIVOS FIJOS AL CIERRE DE GESTIÓN' ,'/EXCELGEN');

INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (15,  'PROVEEDORES' ,'PROVEEDORES' ,'/AFPROVEEDOR/LISTAFPROVEEDOR.XHTML');
INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (16,  'PARTIDAS PRESUPUESTARIAS' ,'PARTIDAS PRESUPUESTARIAS' ,'/AFPARTIDAPRESUPUESTARIA/LISTAFPARTIDAPRESUPUESTARIA.XHTML');
INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (17,  'CODIGOS CONTABLES' ,'CÓDIGOS CONTABLES' ,'/AFCODIGOCONTABLE/LISTAFCODIGOCONTABLE.XHTML');
INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (18,  'FAMILIAS AF' ,'FAMILIAS DE ACTIVOS FIJOS' ,'/AFFAMILIAACTIVO/LISTAFFAMILIAACTIVO.XHTML');
INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (19,  'SUB-FAMILIAS AF','SUB-FAMILIAS DE ACTIVOS FIJOS' ,'/AFSUBFAMILIAACTIVO/LISTAFSUBFAMILIAACTIVO.XHTML');
INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (20,  'AMBIENTES' ,'AMBIENTES' ,'/AFAMBIENTE/LISTAFAMBIENTE.XHTML');
INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (21,  'MATERIALES' ,'MATERIALES' ,'/AFMATERIAL/LISTAFMATERIAL.XHTML');
INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (22,  'ALMACENES' ,'ALMACENES' ,'/AFALMACEN/LISTAFALMACEN.XHTML');
INSERT INTO SEC_RECURSOS (RES_ID, RES_CODREC, RES_DESCRIP, RES_URL) VALUES (23,  'GESTIONES' ,'GESTIONES' ,'/AFGESTION/LISTAFGESTION.XHTML');

-- PROFILE

INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (1, 1);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (1, 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (2 , 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (3, 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (25 , 6);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (5, 6);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (6 , 6);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (6 , 1);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (7, 6);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (8, 6);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (9 , 6);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (10, 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (10, 7);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (11 , 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (12 , 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (12 , 7);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (13,  2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (13,, 7);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (15 , 5);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (15 , 6);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (15 , 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (15 , 3);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (16, 5);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (17 , 5);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (18 , 5);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (19 , 5);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (20 , 5);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (21, 5);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (22 , 5);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (16, 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (17 , 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (18 , 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (19 , 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (20 , 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (21, 6);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (22 , 6);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (23 , 5);