insert into gen_tablas (tab_codigo, tab_descripcion) values (1,'tab auno');
insert into gen_desctabla (des_codtab,    des_codigo ,  des_descrip ) values (1,1,'VALOR UNO');


insert into gen_tablas (tab_codigo, tab_descripcion) values (20,'tab auno');
insert into gen_desctabla (des_codtab,    des_codigo ,  des_descrip ) values (20,1,'VALOR UNO');

-- roles
insert into sec_roles (rol_id, rol_codrol, rol_descrip) values (1, 'USR_ALMACENES', 'USUARIO AAFF Y ALMACENES');
insert into sec_roles (rol_id, rol_codrol, rol_descrip) values (2, 'RESPONSABLE', 'RESPONSABLE AAFF');
insert into sec_roles (rol_id, rol_codrol, rol_descrip) values (3, 'CONTRATACIONES', 'CONTRATACIONES');
insert into sec_roles (rol_id, rol_codrol, rol_descrip) values (5, 'ADM_SISTEMAS', 'ADMINISTRADOR SISTEMAS');
insert into sec_roles (rol_id, rol_codrol, rol_descrip) values (6, 'RESPONSABLE_ALMACENES', 'RESPONSABLE ALMACENES');
insert into sec_roles (rol_id, rol_codrol, rol_descrip) values (7, 'CONTABILIDAD', 'CONTABILIDAD');


-- recursos

INSERT INTO public.SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (1 , 'ASIGNACIONES','MIS ASIGNACIONES');       
INSERT INTO public.SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (2 , 'RECEPCION' ,'RECEPCIÓN' );
INSERT INTO public.SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (3 , 'GESTION AF' ,'GESTION DE ACTIVOS FIJOS');
INSERT INTO public.SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (25 , 'INGRESO DE MATERIALES','INGRESO DE MATERIALES');
INSERT INTO public.SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (5 , 'BAJA DE MATERIALES','BAJA DE MATERIALES');
INSERT INTO public.SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (6 , 'SOLICITUD DE MATERIALES' ,'SOLICITUD DE MATERIALES');
INSERT INTO public.SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (7 , 'KARDEX DE MATERIALES','KARDEX DE MATERIALES');
INSERT INTO public.SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (8 , 'REPORTE EXISTENCIA MATER','REPORTE DE EXISTENCIA DE MATERIALES');
INSERT INTO public.SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (9 , 'REPORTE MOVIMIENTOS POR ALM','REPORTE DE MOVIMIENTOS POR ALMACEN Y MATERIAL');
INSERT INTO public.SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (10,  'BUSCADOR','BUSCADOR AVANZADO DE ACTIVOS FIJOS' );
INSERT INTO public.SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (11,  'ASIGNACION AF' ,'ASIGNACIÓN DE ACTIVOS FIJOS' );
INSERT INTO public.SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (12,  'REPORTE UFV','REPORTE DE UNIDAD DE FOMENTO A LA VIVIENDA');
INSERT INTO public.SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (13,  'INVENTARIO TOTAL AF CIERRE','INVENTARIO TOTAL DE ACTIVOS FIJOS AL CIERRE DE GESTIÓN');
INSERT INTO public.SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (16,  'PARTIDAS PRESUPUESTARIAS' ,'PARTIDAS PRESUPUESTARIAS' );
INSERT INTO public.SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (17,  'CODIGOS CONTABLES' ,'CÓDIGOS CONTABLES');
INSERT INTO public.SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (18,  'FAMILIAS AF' ,'FAMILIAS DE ACTIVOS FIJOS');
INSERT INTO public.SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (19,  'SUB-FAMILIAS AF','SUB-FAMILIAS DE ACTIVOS FIJOS');
INSERT INTO public.SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (20,  'AMBIENTES' ,'AMBIENTES');
INSERT INTO public.SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (23,  'GESTIONES' ,'GESTIONES');
INSERT INTO public.sec_recurso (res_id ,res_codrec, res_descrip) VALUES (35,'USERS','USERS');
INSERT INTO public.sec_recurso (res_id ,res_codrec, res_descrip) VALUES (36,'UNIDADES','UNIDADES');
INSERT INTO public.sec_recurso (res_id ,res_codrec, res_descrip) VALUES (37,'MATERIALES','MATERIALES');
INSERT INTO public.sec_recurso (res_id ,res_codrec, res_descrip) VALUES (38,'ACTIVOSF','ACTIVOSF');
INSERT INTO public.sec_recurso (res_id ,res_codrec, res_descrip) VALUES (39,'ALMACENES','ALMACENES');
INSERT INTO public.sec_recurso (res_id ,res_codrec, res_descrip) VALUES (50,'CODIGOSCONTABLES','CODIGOSCONTABLES');
INSERT INTO public.sec_recurso (res_id ,res_codrec, res_descrip) VALUES (51,'FAMILIASACTIVOS','FAMILIASACTIVOS');
INSERT INTO public.sec_recurso (res_id ,res_codrec, res_descrip) VALUES (52,'KARDEX','KARDEX');
INSERT INTO public.sec_recurso (res_id ,res_codrec, res_descrip) VALUES (53,'PARTIDAS','PARTIDAS');
INSERT INTO public.sec_recurso (res_id ,res_codrec, res_descrip) VALUES (55,'PROVEEDORES','PROVEEDORES');
INSERT INTO public.sec_recurso (res_id ,res_codrec, res_descrip) VALUES (56,'EMPLEADOS','EMPLEADOS');
INSERT INTO public.sec_recurso (res_id ,res_codrec, res_descrip) VALUES (57,'PERSONAS','PERSONAS');
INSERT INTO public.sec_recurso (res_id ,res_codrec, res_descrip) VALUES (58,'ITEMS','ITEMS');
 
-- PROFILE

INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (1, 1);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (1, 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (2 , 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (3, 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (25 , 6);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (5, 6);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (6 , 6);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (6 , 1);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (7, 6);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (8, 6);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (9 , 6);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (10, 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (10, 7);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (11 , 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (12 , 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (12 , 7);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (13,  2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (13,, 7);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (15 , 5);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (15 , 6);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (15 , 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (15 , 3);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (16, 5);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (17 , 5);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (18 , 5);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (19 , 5);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (20 , 5);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (21, 5);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (22 , 5);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (16, 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (17 , 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (18 , 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (19 , 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (20 , 2);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (21, 6);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (22 , 6);
INSERT INTO SEC_PROFILE (PRR_RESID, PRR_ROLID) VALUES (23 , 5);

INSERT INTO public.sec_profile(	prr_resid, prr_rolid)	VALUES (35,5) ;
INSERT INTO public.sec_profile(	prr_resid, prr_rolid)	VALUES (36,5) ;
INSERT INTO public.sec_profile(	prr_resid, prr_rolid)	VALUES (38,5) ;
INSERT INTO public.sec_profile(	prr_resid, prr_rolid)	VALUES (50,5);
INSERT INTO public.sec_profile(	prr_resid, prr_rolid)	VALUES (51,5);
INSERT INTO public.sec_profile(	prr_resid, prr_rolid)	VALUES (52,5);
INSERT INTO public.sec_profile(	prr_resid, prr_rolid)	VALUES (53,5);
INSERT INTO public.sec_profile(	prr_resid, prr_rolid)	VALUES (56,5);








INSERT INTO sec_userrol(	uro_usrid, uro_rolid)	VALUES (17, 1);
INSERT INTO sec_userrol(	uro_usrid, uro_rolid)	VALUES (23, 1);
INSERT INTO sec_userrol(	uro_usrid, uro_rolid)	VALUES (23, 2);
















INSERT INTO SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (25 , 'INGRESO DE MATERIALES','INGRESO DE MATERIALES AFALTAMATERIAL/LISTAFALTAMATERIAL.XHTML');
INSERT INTO SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (5 , 'BAJA DE MATERIALES','BAJA DE MATERIALES AFBAJAMATERIAL/LISTAFBAJAMATERIAL.XHTML');
INSERT INTO SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (6 , 'SOLICITUD DE MATERIALES' ,'SOLICITUD DE MATERIALES  AFSOLICITUDDEMATERIAL/MANAGEAFSOLICITUDDEMATERIAL.XHTML');
INSERT INTO SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (7 , 'KARDEX DE MATERIALES','KARDEX DE MATERIALES REPORTESALMACENES/KARDEXMATERIALALMACEN.XHTML');
INSERT INTO SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (8 , 'REPORTE EXISTENCIA MATER','REPORTE DE EXISTENCIA DE MATERIALES REPORTESALMACENES/REPORTEEXISTENCIAS.XHTML');
INSERT INTO SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (9 , 'REPORTE MOVIMIENTOS POR ALM','REPORTE DE MOVIMIENTOS POR ALMACEN Y MATERIAL REPORTESALMACENES/LISTREGISTROKARDEXMATERIALALMACEN.XHTML');

INSERT INTO SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (10,  'BUSCADOR','BUSCADOR AVANZADO DE ACTIVOS FIJOS  REPORTES/BUSCADORAVANZADO.XHTML');
INSERT INTO SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (11,  'ASIGNACION AF' ,'ASIGNACIÓN DE ACTIVOS FIJOS  REPORTES/ASIGNACIONUSUARIO.XHTML');
INSERT INTO SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (12,  'REPORTE UFV','REPORTE DE UNIDAD DE FOMENTO A LA VIVIENDA  AFTIPOCAMBIO/LISTAFTIPOCAMBIO.XHTML');
INSERT INTO SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (13,  'INVENTARIO TOTAL AF CIERRE','INVENTARIO TOTAL DE ACTIVOS FIJOS AL CIERRE DE GESTIÓN  EXCELGEN');

INSERT INTO SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (15,  'PROVEEDORES' ,'PROVEEDORES  AFPROVEEDOR/LISTAFPROVEEDOR.XHTML');
INSERT INTO SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (16,  'PARTIDAS PRESUPUESTARIAS' ,'PARTIDAS PRESUPUESTARIAS  AFPARTIDAPRESUPUESTARIA/LISTAFPARTIDAPRESUPUESTARIA.XHTML');
INSERT INTO SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (17,  'CODIGOS CONTABLES' ,'CÓDIGOS CONTABLES  AFCODIGOCONTABLE/LISTAFCODIGOCONTABLE.XHTML');
INSERT INTO SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (18,  'FAMILIAS AF' ,'FAMILIAS DE ACTIVOS FIJOS  AFFAMILIAACTIVO/LISTAFFAMILIAACTIVO.XHTML');
INSERT INTO SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (19,  'SUB-FAMILIAS AF','SUB-FAMILIAS DE ACTIVOS FIJOS  AFSUBFAMILIAACTIVO/LISTAFSUBFAMILIAACTIVO.XHTML');
INSERT INTO SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (20,  'AMBIENTES' ,'AMBIENTES  AFAMBIENTE/LISTAFAMBIENTE.XHTML');
INSERT INTO SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (21,  'MATERIALES' ,'MATERIALES  AFMATERIAL/LISTAFMATERIAL.XHTML');
INSERT INTO SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (22,  'ALMACENES' ,'ALMACENES  AFALMACEN/LISTAFALMACEN.XHTML');
INSERT INTO SEC_RECURSO (RES_ID, RES_CODREC, RES_DESCRIP) VALUES (23,  'GESTIONES' ,'GESTIONES  AFGESTION/LISTAFGESTION.XHTML');