CREATE ROLE activosf WITH
	LOGIN
	NOSUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'xxxxxx';

    CREATE DATABASE activosf
    WITH
    OWNER = activosf
    ENCODING = 'UTF8'
    TABLESPACE = datadb
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

    