INSERT INTO gen_tablas (tab_codigo, tab_descripcion) VALUES (101, 'TIPOS DE PERSONA                        ');
INSERT INTO gen_tablas (tab_codigo, tab_descripcion) VALUES (102, 'SEXO                                    ');
INSERT INTO gen_tablas (tab_codigo, tab_descripcion) VALUES (103, 'ESTADO CIVIL                            ');
INSERT INTO gen_tablas (tab_codigo, tab_descripcion) VALUES (104, 'DOCUMENTOS DE IDENTIDAD                 ');
INSERT INTO gen_tablas (tab_codigo, tab_descripcion) VALUES (105, 'MONEDAS                                 ');
INSERT INTO gen_tablas (tab_codigo, tab_descripcion) VALUES (110, 'MONEDAS                                 ');
INSERT INTO gen_tablas (tab_codigo, tab_descripcion) VALUES (176, 'CIUDADES DEL PAIS                       ');
INSERT INTO gen_tablas (tab_codigo, tab_descripcion) VALUES (177, 'ESTADO DEL CLIENTE                      ');
INSERT INTO gen_tablas (tab_codigo, tab_descripcion) VALUES (179, 'PROFESIONES                             ');
INSERT INTO gen_tablas (tab_codigo, tab_descripcion) VALUES (154, 'PAISES                                  ');
INSERT INTO gen_tablas (tab_codigo, tab_descripcion) VALUES (1351, 'TIPOS DE DOCUMENTOS                     ');
INSERT INTO gen_tablas (tab_codigo, tab_descripcion) VALUES (1602, 'ESTADOS                                 ');
INSERT INTO gen_tablas (tab_codigo, tab_descripcion) VALUES (13, 'ESTADO DE REGISTRO');
INSERT INTO gen_tablas (tab_codigo, tab_descripcion) VALUES (18, 'TIPOS DE SOLICITUD');
INSERT INTO gen_tablas (tab_codigo, tab_descripcion) VALUES (31, 'TIPO USUARIO');
INSERT INTO gen_tablas (tab_codigo, tab_descripcion) VALUES (53, 'TIPO DE ACTUALIZACION');


INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (101, 1, 'PERSONA NATURAL                         ', 'P.NAT',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (101, 2, 'SUCESION INDIVISA                       ', 'SUC.I',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (101, 3, 'EMPRESA UNIPERSONAL                     ', 'EMP.U',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (101, 4, 'SOCIEDAD COLECTIVA                      ', 'SOC.C',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (101, 5, 'SOCIEDAD ANONIMA                        ', 'SOC.A',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (101, 6, 'SOCIEDAD EN COMANDITA SIMPLE            ', 'SOC.C',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (101, 7, 'SOCIEDAD EN COMANDITA POR ACCIONES      ', 'SOC.C',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (101, 8, 'SOCIEDAD DE RESPONSABILIDAD LIMITADA    ', 'S.R.L',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (101, 9, 'ASOCIACION ACCIDENTAL O D/CUENTAS EN PAR', 'ASOC.',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (101, 10, 'SOCIEDAD O ENTIDAD CONSTITUIDA EN EL EXT', 'SOC.E',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (101, 11, 'COOPERATIVAS O MUTUALES                 ', 'COOP/',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (101, 12, 'SOCIEDAD SOCIAL, CULTURAL Y DEPORTIVA   ', 'SOC. ',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (101, 13, 'ASOC. O FUNDACIONES RELIGIOSAS Y/O EDUCA', 'SOC. ',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (101, 14, 'EMPRESAS PUBLICAS                       ', 'EMP.P',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (101, 15, 'EMP.PUBLICAS DESCENTRALIZADAS MUNICIP.  ', 'EMP.P',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (101, 16, 'SOCIEDAD DE ECONOMIA MIXTA              ', 'SOC.E',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (101, 17, 'OTRAS NO ESPECIFICADAS                  ', 'OTRAS',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (102, 1, 'MASCULINO                               ', null,  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (102, 2, 'FEMENINO                                ', null,  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (103, 1, 'SOLTERO(A)                              ', null,  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (103, 2, 'CASADO(A)                               ', null,  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (103, 3, 'VIUDA(A)                                ', 'VDA. ',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (104, 1, 'CARNET DE IDENTIDAD                     ', 'C.I. ',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (104, 2, 'REGISTRO UNICO NACIONAL                 ', 'RUN  ',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (104, 3, 'PERSONA EXTRANJERA                      ', 'PE   ',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (104, 4, 'CORRELATIVO PERSONA NATURAL             ', 'CPN  ',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (104, 5, 'REGISTRO UNICO DE CONTRIBUYENTES        ', 'RUC  ',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (104, 6, 'EMPRESA EXTRANJERA                      ', 'EE   ',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (104, 7, 'CORRELATIVO PERSONA JURIDICA            ', 'CPJ  ',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (104, 8, 'POR RESOLUCION                          ', 'PR   ',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (104, 9, 'NUMERO IDENTIFICACION TRIBUTARIA        ', 'NIT  ',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (105, 1, 'BOLIVIANOS               BS.            ', 'Bs.  ',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (105, 2, 'DOLARES                  $US.           ', '$us. ',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (105, 3, 'MANTENIMIENTO DE VALOR                  ', 'MV.  ',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (105, 4, 'MONEDA NACIONAL CMV UFV                 ', 'UFV  ',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (176, 1, 'SANTA CRUZ                              ', 'SCZ  ',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (176, 2, 'LA PAZ                                  ', 'LPZ  ',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (176, 3, 'COCHABAMBA                              ', 'CBBA ',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (176, 4, 'ORURO                                   ', 'ORURO',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (176, 5, 'TARIJA                                  ', 'TARJA',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (176, 6, 'SUCRE                                   ', null,  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (176, 7, 'BENI                                    ', null,  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (177, 1, 'ACTIVO                                  ', null,  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (177, 9, 'INACTIVO                                ', null,  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (1351, 1, 'FACTURA COMERCIAL                       ', null,  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (1351, 2, 'CONOMICIMIENTO DE EMBARQUE MARITIMO     ', null,  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (1351, 3, 'GUIA CAMIONERA                          ', null,  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (1351, 4, 'GUIA DE FERROCARRIL                     ', null,  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (1351, 5, 'GUIA AEREA                              ', null,  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (1351, 6, 'CERTIFICADO DE ORIGEN                   ', null,  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (1351, 7, 'LISTA DE EMPAQUE                        ', null,  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (1351, 8, 'CERTIFICADO FITOSANITARIO               ', null,  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (1351, 9, 'CERTIFICADO DE INSPECCION P. IMPORT.    ', null,  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (1351, 10, 'POLIZA/CERTIFICADO DE SEGURO            ', null,  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (1602, 1, 'PENDIENTE                               ', '',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (1602, 2, 'HABILITADO                              ', '',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (1602, 7, 'BLOQUEADO                               ', '',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (1602, 8, 'PAGADO                                  ', '',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (1602, 9, 'ANULADO                                 ', '',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (13, 0, 'VIGENTE', null,  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (13, 9, 'SUSPENDIDO', null,  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (31, 1, 'MODIFICA', 'OPE',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (31, 2, 'SUPERVISA', 'PRE',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (31, 3, 'AUTORIZA', 'AUT',  null, null);
INSERT INTO gen_desctabla (des_codtab, des_codigo, des_descrip, des_codeiso,  des_auditusr,  des_auditwst) VALUES (31, 4, 'CONSULTA', 'CONS',  null, null);
