server:
  port: 3000

spring:
#  config:
#    activate:
#      on-profile: local
     
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/activosf
    username: activosf
    password: qazwsx

  jpa:
    #show-sql: true  
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: none
        
    properties:
      hibernate:
        default_batch_fetch_size: 500
        #format_sql: true
        #use_sql_comments: true

security:
  key:
    private: classpath:app.key
    public: classpath:app.pub
  authentication:
    jwt:
      # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
      base64-secret: NDJmOTVlZjI2NzhlZDRjNmVkNTM1NDE2NjkyNDljZDJiNzBlMjI5YmZjMjY3MzdjZmZlMjI3NjE4OTRkNzc5MWYzNDNlYWMzYmJjOWRmMjc5ZWQyZTZmOWZkOTMxZWZhNWE1MTVmM2U2NjFmYjhlNDc2Y2Q3NzliMGY0YzFkNmI=
decorator:
  datasource:
    p6spy:
      enable-logging: true

# swagger

springdoc:
  swagger-ui:
    path: /activosf-documentation
    tryItOutEnabled: true
    ui.filter: true
  api-docs:
    path: /activosf-api-docs

activosf:
  openapi:
    dev-url: http://localhost:3000
    prod-url: https://gob.gamo.org
  jwt:
    sessionTimeout: 900

